# standard jekyll configuration
markdown:         rdiscount
pygments:         true
paginate:         10     //the number of post per page
permalink:        /:year/:month/:day/:title.html
safe:             true
lsi:              false
excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# configuration required for some pages
title:            Fan's Blog
url:              http://fanhongtao.github.io
feed:             /atom.xml
author:
    name:         Fan Hongtao
    email:        fanhongtao@gmail.com
description:      "Fan's Blog"

about: 			  "I am Fan Hongtao, a programmer working with Android."

blogName: 		  Fan's Blog
blogDesc: 		  Program, Economy & Life.

# configuration for ehancements, uncomment to enable
github:
    username: fanhongtao

