# standard jekyll configuration
markdown:         rdiscount
pygments:         true
paginate:         4

# configuration required for some pages
title:            Fan's Blog
# url:              http://www.pizn.me
feed:             /atom.xml
author:
    name:         Fan Hongtao
    email:        fanhongtao@gmail.com
description:      "Fan's Blog"

about: 			  "I am Fan Hongtao, a programmer working with Android."
follow:
    github:       https://github.com/fanhongtao

blogName: 		  Fan's Blog
blogDesc: 		  Program, Economy & Life.

# configuration for ehancements, uncomment to enable
github:
    username: fanhongtao

